### ISSUE TITLE
Support a "has footer" configuration option.

### ISSUE THREAD

**Issue by JoeGermuska** [propublica/table-fu#5]
I have a table with a totals row. I'd like to be able to handle that row separately in a TableSetter project (that is, wrap it in <tfoot> tags).  TableFu could accept a configuration option that indicates that the last row should be treated specially.

**Comment by thejefflarson** [comment]
Sorry for the late reply. Geez.

Hm, yeah the way we usually do that is have a `fix_last_row` declaration in the yaml and then use the table's total_for column to build out a tfoot. something like:

https://gist.github.com/893422

The trick is to remember that yaml declarations get attached to the table object in the view.
